using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MedCore.Claim;
using System.IO;
using Newtonsoft.Json;
using System.Diagnostics;
using MedCore.Tests.Objects;

namespace MedCore.Tests
{
    [TestFixture]
    public class GpTest
    {
        private GpClaim gpClaim;
        private string gpFile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "MedCore\\Claims\\Gp.json");

        [SetUp]
        public void Setup()
        {
            if (!File.Exists(gpFile))
            {
                // No claim file has been generated. Generate a claim and write it to a file.
                var testClaim = new TestGpClaim();
                testClaim.WriteGpJson();
            }
            using (var file = File.OpenText(gpFile))
            {
                var serializer = new JsonSerializer();
                gpClaim = (GpClaim)serializer.Deserialize(file, typeof(GpClaim));
            }            
        }

        [Test]
        public void GenerateGpClaim()
        {
            // Value generated by project.
            var output = gpClaim.GenerateClaim();

            // Example value to test against.
            var testClaim = new TestGpClaim();
            var actual = testClaim.GetGpActual();

            Assert.That(output, Is.EqualTo(actual));
        }
    }
}
