using NUnit.Framework;
using System;
using System.IO;
using MedCore.Tests.Claims;
using Newtonsoft.Json;

namespace MedCore.Tests
{
    [TestFixture]
    public class GpTest
    {
        private GpClaim _gpClaim;
        private string _gpFile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "MedCore\\Claims\\Gp.json");

        [SetUp]
        public void Setup()
        {
            if (!File.Exists(_gpFile))
            {
                // No claim file has been generated. Generate a claim and write it to a file.
                var testClaim = new TestGpClaim();
                testClaim.WriteGpJson();
            }
            using (var file = File.OpenText(_gpFile))
            {
                var serializer = new JsonSerializer();
                _gpClaim = (GpClaim)serializer.Deserialize(file, typeof(GpClaim));
            }            
        }

        [Test]
        public void GenerateGpClaim()
        {
            // Value generated by project.
            var output = _gpClaim.GenerateClaim();

            // Example value to test against.
            var testClaim = new TestGpClaim();
            var actual = testClaim.GetGpActual();

            Assert.That(output, Is.EqualTo(actual));
        }
    }
}
